#!/usr/bin/env python

Import("env")
Import("env_modules")

env_inotify = env_modules.Clone()

env_inotify.Prepend(CPPPATH=[Dir(".").abspath])
env_inotify.add_source_files(env.modules_sources, "*.cpp")
